kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: httpd-data-pvc
  namespace: httpd-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: standard-csi
  volumeMode: Block
