---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: windows-install-image-edit
  namespace: kubevirt-os-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi.kubevirt.io:edit
subjects:
- kind: ServiceAccount
  name: windows-install
  namespace: kubevirt-gitops
