---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhelvm-from-argocd
  namespace: rhelvm-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: rhelvm-from-argocd
    app.kubernetes.io/part-of: vms
    app.openshift.io/runtime: kubevirt
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: rhelvm-from-argocd-disk0
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Block
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        flavor.template.kubevirt.io/small: 'true'
        kubevirt.io/domain: rhelvm-from-argocd
        kubevirt.io/size: small
        os.template.kubevirt.io/rhel8.5: 'true'
        vm.kubevirt.io/name: rhelvm-from-argocd
        workload.template.kubevirt.io/server: 'true'
        node_type: test
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      hostname: rhelvm-from-argocd
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: cloud-user
              password: 'Passw0rd'
              chpasswd:
                expire: false
          name: cloudinitdisk
        - dataVolume:
            name: rhelvm-from-argocd-disk0
          name: rootdisk
