apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- windows-install-rbac.yaml


patches:
 - target:
      group: cdi.kubevirt.io
      version: v1beta1
      kind: DataVolume
      name: win2k19-install-iso
   path: http-patch.yaml
